-- MySQL Script generated by MySQL Workbench
-- 04/28/17 01:19:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wazpital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wazpital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wazpital` DEFAULT CHARACTER SET utf8 ;
USE `wazpital` ;

-- -----------------------------------------------------
-- Table `wazpital`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Hospital` (
  `codHospital` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codHospital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Country` (
  `codCountry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`State`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`State` (
  `codState` INT NOT NULL,
  `codCountry` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codState`, `codCountry`),
  INDEX `fk_State_Country1_idx` (`codCountry` ASC),
  CONSTRAINT `fk_State_Country1`
    FOREIGN KEY (`codCountry`)
    REFERENCES `wazpital`.`Country` (`codCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`City` (
  `codCity` INT NOT NULL,
  `codCountry` INT NOT NULL,
  `codState` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codCity`, `codCountry`, `codState`),
  INDEX `fk_City_State1_idx` (`codCountry` ASC, `codState` ASC),
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`codCountry` , `codState`)
    REFERENCES `wazpital`.`State` (`codCountry` , `codState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Address` (
  `codHospital` INT NOT NULL,
  `number` INT NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `zipCode` VARCHAR(45) NOT NULL,
  `neighborhood` VARCHAR(255) NOT NULL,
  `coordinateX` DOUBLE NOT NULL,
  `coordinateY` VARCHAR(45) NOT NULL,
  `codCity` INT NOT NULL,
  `codCountry` INT NOT NULL,
  `codState` INT NOT NULL,
  PRIMARY KEY (`codHospital`),
  INDEX `fk_Address_City1_idx` (`codCity` ASC, `codCountry` ASC, `codState` ASC),
  CONSTRAINT `fk_Address_Hospital`
    FOREIGN KEY (`codHospital`)
    REFERENCES `wazpital`.`Hospital` (`codHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_City1`
    FOREIGN KEY (`codCity` , `codCountry` , `codState`)
    REFERENCES `wazpital`.`City` (`codCity` , `codCountry` , `codState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`HealthCare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`HealthCare` (
  `codHealthCare` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codHealthCare`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`Hospital_has_HealthCare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Hospital_has_HealthCare` (
  `codHospital` INT NOT NULL,
  `codHealthCare` INT NOT NULL,
  PRIMARY KEY (`codHospital`, `codHealthCare`),
  INDEX `fk_Hospital_has_HealthCare_HealthCare1_idx` (`codHealthCare` ASC),
  INDEX `fk_Hospital_has_HealthCare_Hospital1_idx` (`codHospital` ASC),
  CONSTRAINT `fk_Hospital_has_HealthCare_Hospital1`
    FOREIGN KEY (`codHospital`)
    REFERENCES `wazpital`.`Hospital` (`codHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_HealthCare_HealthCare1`
    FOREIGN KEY (`codHealthCare`)
    REFERENCES `wazpital`.`HealthCare` (`codHealthCare`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Contact` (
  `codContact` INT NOT NULL,
  `codHospital` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codContact`, `codHospital`),
  INDEX `fk_Contact_Hospital1_idx` (`codHospital` ASC),
  CONSTRAINT `fk_Contact_Hospital1`
    FOREIGN KEY (`codHospital`)
    REFERENCES `wazpital`.`Hospital` (`codHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`Specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Specialization` (
  `codSpecialization` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`codSpecialization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`Hospital_has_Specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Hospital_has_Specialization` (
  `codHospital` INT NOT NULL,
  `codSpecialization` INT NOT NULL,
  PRIMARY KEY (`codHospital`, `codSpecialization`),
  INDEX `fk_Hospital_has_Specialization_Specialization1_idx` (`codSpecialization` ASC),
  INDEX `fk_Hospital_has_Specialization_Hospital1_idx` (`codHospital` ASC),
  CONSTRAINT `fk_Hospital_has_Specialization_Hospital1`
    FOREIGN KEY (`codHospital`)
    REFERENCES `wazpital`.`Hospital` (`codHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_has_Specialization_Specialization1`
    FOREIGN KEY (`codSpecialization`)
    REFERENCES `wazpital`.`Specialization` (`codSpecialization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`User` (
  `codUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `birthDate` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`Rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`Rate` (
  `timeRate` DATETIME NOT NULL,
  `codHospital` INT NOT NULL,
  `codUser` INT NOT NULL,
  `overflowingLevel` INT NOT NULL,
  `attendanceSpeed` INT NOT NULL,
  `attendanceRate` INT NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`timeRate`, `codHospital`, `codUser`),
  INDEX `fk_Rate_Hospital1_idx` (`codHospital` ASC),
  INDEX `fk_Rate_User1_idx` (`codUser` ASC),
  CONSTRAINT `fk_Rate_Hospital1`
    FOREIGN KEY (`codHospital`)
    REFERENCES `wazpital`.`Hospital` (`codHospital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rate_User1`
    FOREIGN KEY (`codUser`)
    REFERENCES `wazpital`.`User` (`codUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wazpital`.`HealthDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wazpital`.`HealthDocument` (
  `codHealthDocument` INT NOT NULL,
  `codUser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`codHealthDocument`, `codUser`),
  INDEX `fk_HealthDocument_User1_idx` (`codUser` ASC),
  CONSTRAINT `fk_HealthDocument_User1`
    FOREIGN KEY (`codUser`)
    REFERENCES `wazpital`.`User` (`codUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
